#!/bin/bash
echo "=====Adding file to git====="
git add .
echo "=====Finished adding file to git====="

echo
echo
echo


echo "=====Commiting file to git====="
filenames=$( git status | grep "modified" )
#echo $filenames
git commit -m "$filenames"
echo "=====Finished commiting file to git====="

echo
echo

echo "=====Pushing to GitHub Arthur Branch====="
git push
echo "=====Finished pushing to GitHub Arthur Branch====="



echo "=====Firebase Deploying====="

firebase deploy;


#
#  Created by Kuan-Ting Wu on 2018/2/3.
#  
